---
title: "Data Formats"
author: "Morgan Feeney, Leighton Pritchard"
date: "2021 Presentation"
output: 
  bookdown::html_document2:
    toc: true
    toc_float:
      toc_collapsed: false
    number_sections: true
    css: "css/rmd_style.css"
    theme: lumen
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


<div id="summary">

</div>

# Data Formats 

Depending on the type of project and the analysis you are doing, you may end up generating and dealing with a number of different data formats. 

Understanding what type of data you generate, and how it is formatted, is a key part of experimental design. *Before* you perform an experiment, you should already have a good idea of what kind of data it will generate, how you will record it, and how it will be formatted and stored. This is part of a good data management strategy, and making these decisions before performing the experiment can help to avoid introducing unconscious biases that might affect the results. 

Different types of experiment generate different types of data, which can be formatted in a variety of ways. 

<details>
  <summary>Click to expand an example of how data can be generated and stored in different formats</summary>
For example, you might analyse the size of DNA fragments using gel electrophoresis, and take an image of the resulting gel using a gel doc. This produces an image, which can be saved as an image file, printed out and pasted in your lab notebook, and interpreted. 

The raw data generated by this experiment is the image file. You might also generate a list of DNA fragment sizes, from comparing the sizes of your DNA fragments to standards of known size (the DNA ladder). This is also data and it can be stored in a number of different formats (perhaps a handwritten list in your lab notebook, or as a list in a .txt, .csv, or .docx file. - you might choose any of these formats, based on what is most compatible with the downstream analyses that will be performed on these data, what is most compatible with [FAIR principles](./02b-reproducibility.html), and most convenient for you and your colleagues working on the project.)

#Add additional examples? something bioinformatics something? 
</details>

<div id="warning">
Regardless of any downstream analyses or data formatting/reformatting decisions, you must *always* save that original copy of the raw data - this is a fundamental principle of good scientific practice. 

You must always be able to return to the original data *in the form it was originally collected/recorded*. 
</div>

<div id="note">
Data are often associated with *metadata* - data that provide information about the data. 

These data may be in a different format to the data itself (e.g., a text file describing the sample characteristics and other metadata, paired with the sequencing reads obtained from that sample; or, the date and GPS coordinates at which a photograph were taken.)

Without the metadata, the data themselves would lack context and may even be uninterpretable/unusable. It is therefore important that your plan for data management includes a plan for how you will accurately record, format, and store the metadata for your experiments.)
</div>


## Binary (if really necessary) vs Human-readable (better)

## Tabular data

As scientists, we often generate, work with, or analyse data in a tabular format (tables with rows and columns.) ^[More information about how to organise these data is covered in [datasets](./03-dataset.html).]

### XLSX vs CSV vs TAB vs...


## Image data
### Bitmap (not scalable) vs Vector (scalable) images
### TIFF files (preserve original data!)

## Specialised data examples
### FASTA vs FASTQ vs …
### BLAST outputs
### Survey data

# How Should My Data Be Formatted? 

# Converting Between Different Data Formats

