---
title: "Data Management Workshop"
author: "Leighton Pritchard, Morgan Feeney"
date: "2022 Presentation"
output: 
  bookdown::html_document2:
    toc: true
    toc_float:
      toc_collapsed: false
    number_sections: true
    css: "css/rmd_style.css"
    theme: lumen
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<div id="summary">
- This is the landing page for the 2022-10-05 workshop on data management
- Please read and work through the pages linked below
</div>

# Workshop 3: "Project Management" (Wednesday 5th October 2022, 9-11am)

- [01-Data Analysis in the Research Cycle](./03-01-data_analysis.html)
- [02-Data and Project Management](./03-02-project_management.html)
- [03-Reproducibility, Replicability, and FAIR Guidelines](./03-03-reproducibility.html)
- [04-Keeping a Lab Notebook to Document Your Project](./03-04-keeping_a_lab_notebook.html)
- [05-Reference Management](./03-05-reference_management.html)
- [06-How to Use Reference Management Software](./03-06-using_a_reference_manager.html)

## Example lab notebooks and Google form

- Please read through at least one of the sets of example lab notebooks (provided for you on MyPlace and also linked below for your convenience)
  - You may find it most helpful to choose the set of notebooks that is most similar to your project type
  - You may choose to work through more than 1 set of notebooks, if you wish to do so (please fill out the Google form separately for each set)
- Please fill out this [Google form](https://forms.gle/WoSvnybRBrA8H6qa6) regarding the set of example lab notebooks that you read - <b>before close of play on Monday October 3rd</b> (to give us time to compile your responses before the workshop on Weds)

### Set A: wet-lab notebooks

- [Example A1](../assets/pdfs/lab_notebooks/example_lab_notebook_A1.pdf)
- [Example A2](assets/pdfs/lab_notebooks/example_lab_notebook_A2.pdf)
- [Example A3](assets/pdfs/lab_notebooks/example_lab_notebook_A3.pdf)
- [Example A4](assets/pdfs/lab_notebooks/example_lab_notebook_A4.pdf)

### Set B: bioinformatics notebooks

- [Example B1](assets/pdfs/lab_notebooks/example_bioinformatics_notebook_B1.pdf)
- [Example B2](assets/pdfs/lab_notebooks/example_bioinformatics_notebook_B2.pdf)
- [Example B3](assets/pdfs/lab_notebooks/example_bioinformatics_notebook_B3.pdf)
- [Example B4](assets/pdfs/lab_notebooks/example_bioinformatics_notebook_B4.pdf)

### Set C: critical analysis notebooks

- [Example C1](assets/pdfs/lab_notebooks/example_critical-analysis_notebook_C1.pdf)
- [Example C2](assets/pdfs/lab_notebooks/example_critical-analysis_notebook_C2.pdf)
- [Example C3](assets/pdfs/lab_notebooks/example_critical-analysis_notebook_C3.pdf)
- [Example C4](assets/pdfs/lab_notebooks/example_critical-analysis_notebook_C4.pdf)

### Set D: education notebooks

- [Example D1](assets/pdfs/lab_notebooks/example_education_notebook_D1.pdf)
- [Example D2](assets/pdfs/lab_notebooks/example_education_notebook_D2.pdf)
- [Example D3](assets/pdfs/lab_notebooks/example_education_notebook_D3.pdf)
- [Example D4](assets/pdfs/lab_notebooks/example_education_notebook_D4.pdf)

